import { createStore } from 'vuex';

export default createStore({
  state: {
    questions: [
      ' Can you provide an example of a situation where you used PHP to optimize the performance of a web application? How did you approach the optimization process? - PHP',
      " Can you explain the concept of 'closures' in JavaScript and provide an example of how they can be useful in coding? ",
      ' How would you explain the concept of list comprehensions in Python and provide an example of when you would use them in your code? ',
      ' Can you explain the concept of Eloquent ORM and how it is used in Laravel? ',
      ' Can you explain the concept of state and props in React and how they are used to manage data and communicate between components? ',
    ],
    skills: [
      'PHP',
      'JavaScript',
      'Python',
      'Laravel',
      'React',
      'NestJS',
      'Angular',
      'React Native',
      'Node',
      'MySQL',
      'MongoDB',
      'Redis',
      'Docker',
      'Machine Learning',
      'Communication',
      'Problem-solving',
      'Adaptability',
      'Innovation',
      'Time management',
      'Attention to detail',
      'Leadership',
    ],
    experience: {
      'experience:': [
        'total: 10 years',
        'PHP: 9 years',
        'JavaScript: 6 years',
        'React: 4 years',
        'React Native: 3 years',
        'Node: 2 years',
        'Laravel: 4 years',
        'Python: 2 years',
        'NestJS: 1 year',
        'Angular: 0 years',
        'MySQL: 0 years',
        'MongoDB: 0 years',
        'Redis: 0 years',
        'Docker: 0 years',
        'Machine Learning: 0 years',
      ],
    },
    resume: {
      '- Contact:': [
        'Email: jaffemarquessilva@gmail.com',
        'Phone: 81989659700',
      ],
      '- Professional Summary:': [
        'Technology enthusiast and programmer',
        'Experience leading skilled teams in PHP Formation',
        'Main areas of expertise: PHP, JavaScript, Python, Laravel, React, NestJS, Angular, React Native, Node, MySQL, MongoDB, Redis, Docker, Machine Learning',
        'Possess soft skills in communication, problem-solving, adaptability, innovation, time management, attention to detail, leadership',
      ],
      '- Education:': [
        'PUC Minas (2023 - 2024) - Postgraduate Degree, Software Architecture',
        'UNINTER (2023 - 2024) - Graduate, Data Scientist',
        'UFAPE (completed sixth semester) - Computer Science',
        'IFPE (2012 - 2015) - Technical, Internet Development',
      ],
      '- Certificates:': [
        "Google API Design and Fundamentals of Google Cloud's Apigee API Platform",
        'Alura PHP Training',
        'Alura PHP and TDD: Testing with PHPUnit',
      ],
      '- Experience:': [
        'AEG MEDIA (2015 - 2019) - Full Stack Developer',
        'Genesys V.A (2019 - 2020) - Full Stack Developer',
        'SolarView (2021 - 2021) - Full Stack Developer',
        'Movida Aluguel de Carros (2021 - current) - IT Coordinator',
      ],
    },
  },
  mutations: {},
  actions: {},
  getters: {},
});
